spring.application.name=module_user
spring.datasource.url=jdbc:mysql://localhost:3306/db_crm
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
server.port=8080